In [37]:
import pandas as pd
import numpy as np

In [38]:
# 1 Pandas Series — Marks
marks = pd.Series([78, 85, 92, 67, 88])

print("Complete Series:")
print(marks)

print("\nValues:")
print(marks.values)

print("\nIndex:")
print(marks.index)

print("\nData type:")
print(marks.dtype)

print("\nMean:")
print(marks.mean())

print("\nMaximum:")
print(marks.max())

print("\nMinimum:")
print(marks.min())

Complete Series:
0    78
1    85
2    92
3    67
4    88
dtype: int64

Values:
[78 85 92 67 88]

Index:
RangeIndex(start=0, stop=5, step=1)

Data type:
int64

Mean:
82.0

Maximum:
92

Minimum:
67

In [39]:
# 2. Series with Student Names

marks = pd.Series(
    [85, 78, 92, 74, 88],
    index=["Asha", "Ravi", "Meena", "Kiran", "Arun"]
)

print(marks)

print("\nMarks of Meena:")
print(marks["Meena"])

Asha     85
Ravi     78
Meena    92
Kiran    74
Arun     88
dtype: int64

Marks of Meena:
92

In [40]:
# 3. Create DataFrame
data = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Age": [22, 23, 21, 24, 22],
    "Department": ["CSE", "ECE", "CSE", "ME", "ECE"],
    "Marks": [85, 78, 92, 74, 88]
}

df = pd.DataFrame(data)

print("Complete DataFrame:")
print(df)

print("\nFirst 3 rows:")
print(df.head(3))

print("\nLast 2 rows:")
print(df.tail(2))

Complete DataFrame:
    Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
3  Kiran   24         ME     74
4   Arun   22        ECE     88

First 3 rows:
    Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92

Last 2 rows:
    Name  Age Department  Marks
3  Kiran   24         ME     74
4   Arun   22        ECE     88

In [41]:
print("\nShape:---")
print(df.shape)

print("\nColumn names:")
print(df.columns)

print("\nData types:---\n")
print(df.dtypes)

Shape:---
(5, 4)

Column names:
Index(['Name', 'Age', 'Department', 'Marks'], dtype='str')

Data types:---

Name            str
Age           int64
Department      str
Marks         int64
dtype: object

In [42]:
#4. info(), describe(), Rows and Columns
print("Info:-\n")
df.info()
#print("\n")

print("\nDescribe:-\n")
print(df.describe())

print("\nNumber of rows:-\n")
print(df.shape[0])

print("\nNumber of columns:-")
print(df.shape[1])

Info:-

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      str
 1   Age         5 non-null      int64
 2   Department  5 non-null      str
 3   Marks       5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

Describe:-

             Age      Marks
count   5.000000   5.000000
mean   22.400000  83.400000
std     1.140175   7.334848
min    21.000000  74.000000
25%    22.000000  78.000000
50%    22.000000  85.000000
75%    23.000000  88.000000
max    24.000000  92.000000

Number of rows:-

5

Number of columns:-
4

In [43]:
#5. 
# Selecting Name Column

In [44]:
df[["Name"]]

    Name
0   Asha
1   Ravi
2  Meena
3  Kiran
4   Arun

In [45]:
df[["Marks"]]    # marks

   Marks
0     85
1     78
2     92
3     74
4     88

In [46]:
df[["Name", "Marks"]]   # name & marks

    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3  Kiran     74
4   Arun     88

In [47]:
#6. Using iloc and loc

In [48]:
print(df.iloc[0])  # First row using iloc

Name          Asha
Age             22
Department     CSE
Marks           85
Name: 0, dtype: object

In [49]:
print(df.iloc[2])    #Third row using iloc

Name          Meena
Age              21
Department      CSE
Marks            92
Name: 2, dtype: object

In [50]:
print(df.iloc[1:4])   #Rows 1 to 3

    Name  Age Department  Marks
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
3  Kiran   24         ME     74

In [51]:
#Name and Marks using loc
print(df.loc[:, ["Name", "Marks"]])

    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3  Kiran     74
4   Arun     88

In [52]:
#7. Filtering Data

print(df[df["Marks"] > 80])

    Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92
4   Arun   22        ECE     88

In [53]:
print(df[(df["Marks"] >= 75) & (df["Marks"] <= 90)])

   Name  Age Department  Marks
0  Asha   22        CSE     85
1  Ravi   23        ECE     78
4  Arun   22        ECE     88

In [54]:
print(df[df["Marks"].between(75, 90)])

   Name  Age Department  Marks
0  Asha   22        CSE     85
1  Ravi   23        ECE     78
4  Arun   22        ECE     88

In [55]:
print(df[df["Department"] == "CSE"])

    Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92

In [56]:

print(df[(df["Department"] == "CSE") & (df["Marks"] > 80)])

    Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92

In [57]:
# 8. Students belonging to CSE or ECE

print(df[df["Department"].isin(["CSE", "ECE"])])

    Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
4   Arun   22        ECE     88

In [58]:
#9. Add Result Column

df["Result"] = np.where(df["Marks"] >= 75, "Pass", "Fail")

print(df)

    Name  Age Department  Marks Result
0   Asha   22        CSE     85   Pass
1   Ravi   23        ECE     78   Pass
2  Meena   21        CSE     92   Pass
3  Kiran   24         ME     74   Fail
4   Arun   22        ECE     88   Pass

In [59]:
#10. Add Grade Column
def grade(marks):
    if marks >= 90:
        return "A"
    elif marks >= 80:
        return "B"
    elif marks >= 70:
        return "C"
    else:
        return "D"

df["Grade"] = df["Marks"].apply(grade)

print(df)

    Name  Age Department  Marks Result Grade
0   Asha   22        CSE     85   Pass     B
1   Ravi   23        ECE     78   Pass     C
2  Meena   21        CSE     92   Pass     A
3  Kiran   24         ME     74   Fail     C
4   Arun   22        ECE     88   Pass     B

In [ ]:
#11. Sorting Students

In [61]:
#Marks ascending
print(df.sort_values("Marks"))

print("\n")
#Marks descending
print(df.sort_values("Marks", ascending=False))

    Name  Age Department  Marks Result Grade
3  Kiran   24         ME     74   Fail     C
1   Ravi   23        ECE     78   Pass     C
0   Asha   22        CSE     85   Pass     B
4   Arun   22        ECE     88   Pass     B
2  Meena   21        CSE     92   Pass     A


    Name  Age Department  Marks Result Grade
2  Meena   21        CSE     92   Pass     A
4   Arun   22        ECE     88   Pass     B
0   Asha   22        CSE     85   Pass     B
1   Ravi   23        ECE     78   Pass     C
3  Kiran   24         ME     74   Fail     C

In [62]:
#Department and then Marks
print(df.sort_values(["Department", "Marks"]))

    Name  Age Department  Marks Result Grade
0   Asha   22        CSE     85   Pass     B
2  Meena   21        CSE     92   Pass     A
1   Ravi   23        ECE     78   Pass     C
4   Arun   22        ECE     88   Pass     B
3  Kiran   24         ME     74   Fail     C

In [63]:
#12. Missing Values
data = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Age": [22, 23, np.nan, 24, 22],
    "Marks": [85, np.nan, 92, 74, 88]
}

students = pd.DataFrame(data)

print("DataFrame:")
print(students)

print("\nMissing values:")
print(students.isnull())

print("\nNumber of missing values in each column:")
print(students.isnull().sum())

print("\nRows containing missing values:")
print(students[students.isnull().any(axis=1)])

DataFrame:
    Name   Age  Marks
0   Asha  22.0   85.0
1   Ravi  23.0    NaN
2  Meena   NaN   92.0
3  Kiran  24.0   74.0
4   Arun  22.0   88.0

Missing values:
    Name    Age  Marks
0  False  False  False
1  False  False   True
2  False   True  False
3  False  False  False
4  False  False  False

Number of missing values in each column:
Name     0
Age      1
Marks    1
dtype: int64

Rows containing missing values:
    Name   Age  Marks
1   Ravi  23.0    NaN
2  Meena   NaN   92.0

In [64]:
#13. Replace Missing Values with Average
students["Age"] = students["Age"].fillna(students["Age"].mean())

students["Marks"] = students["Marks"].fillna(students["Marks"].mean())

print(students)

    Name    Age  Marks
0   Asha  22.00  85.00
1   Ravi  23.00  84.75
2  Meena  22.75  92.00
3  Kiran  24.00  74.00
4   Arun  22.00  88.00

In [67]:
#14. Remove Rows Containing Missing Values

students = students.dropna() # updates the actual dataframe

print(students ,"\n")

#don't want to permanently change the DataFrame then
print(students.dropna())

    Name    Age  Marks
0   Asha  22.00  85.00
1   Ravi  23.00  84.75
2  Meena  22.75  92.00
3  Kiran  24.00  74.00
4   Arun  22.00  88.00

    Name    Age  Marks
0   Asha  22.00  85.00
1   Ravi  23.00  84.75
2  Meena  22.75  92.00
3  Kiran  24.00  74.00
4   Arun  22.00  88.00

In [68]:
#15. Find and Remove Duplicates

data = {
    "Name": ["Asha", "Ravi", "Meena", "Asha", "Arun"],
    "Marks": [85, 78, 92, 85, 88]
}

df2 = pd.DataFrame(data)

print("DataFrame:")
print(df2)

print("\nDuplicate rows:")
print(df2[df2.duplicated()])

print("\nAfter removing duplicates:")
print(df2.drop_duplicates())

DataFrame:
    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3   Asha     85
4   Arun     88

Duplicate rows:
   Name  Marks
3  Asha     85

After removing duplicates:
    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
4   Arun     88

In [69]:
#16. Statistical Calculations
marks = pd.DataFrame(
    {
    "Student": ["A", "B", "C", "D", "E"],
    "Marks": [78, 85, 92, 67, 88]
    }
)

print("Mean:", marks["Marks"].mean())
print("Median:", marks["Marks"].median())
print("Maximum:", marks["Marks"].max())
print("Minimum:", marks["Marks"].min())
print("Standard deviation:", marks["Marks"].std())
print("Sum:", marks["Marks"].sum())

Mean: 82.0
Median: 85.0
Maximum: 92
Minimum: 67
Standard deviation: 9.82344135219425
Sum: 410

In [70]:
#17. GroupBy — Department Analysis
data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya"
    ],
    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE"
    ],
    "Marks": [
        85, 78, 92,
        74, 88, 80
    ]
}

df = pd.DataFrame(data)

In [ ]:
#Average marks by department

print(df.groupby("Department")["Marks"].mean())

Department
CSE    85.666667
ECE    83.000000
ME     74.000000
Name: Marks, dtype: float64

In [72]:
#Maximum marks by department

print(df.groupby("Department")["Marks"].max())

Department
CSE    92
ECE    88
ME     74
Name: Marks, dtype: int64

In [73]:
#Number of students

print(df.groupby("Department")["Name"].count())

Department
CSE    3
ECE    2
ME     1
Name: Name, dtype: int64

In [ ]:
df.groupby("Department")["Marks"].agg(["mean_or_avg", "min", "max", "count"])

AttributeError: 'SeriesGroupBy' object has no attribute 'mean(avg)'