In [75]:
print("Lab 3---")

Lab 3---

In [76]:
print("Data Processing --")

Data Processing --

In [77]:
pip install pandas

Requirement already satisfied: pandas in .\.venv-1\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in .\.venv-1\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv-1\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv-1\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in .\.venv-1\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [78]:
import numpy as np
import pandas as pd 
#import matplotlib.pyplot as plt

In [79]:
df = pd.read_csv("D:\Practice_SMJ\Aml-Lab-3-datasets\Data.csv")
print(df)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3  Germany  40.0      NaN       Yes
4    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

<>:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
<>:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
C:\Users\bda\AppData\Local\Temp\ipykernel_19652\4106212845.py:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
  df = pd.read_csv("D:\Practice_SMJ\Aml-Lab-3-datasets\Data.csv")

In [80]:
df.head() # to dsiplay 1st 5 records

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3  Germany  40.0      NaN       Yes
4    Spain  38.0  61000.0        No

In [81]:
df.tail() # last 5 records

   Country   Age   Salary Purchased
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [82]:
 # no of row and columns
print(df.shape)

(10, 4)

In [83]:
df

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3  Germany  40.0      NaN       Yes
4    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [84]:
df.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='str')

In [85]:
df.dtypes  # to know data types of each feild / column

Country          str
Age          float64
Salary       float64
Purchased        str
dtype: object

In [86]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    10 non-null     str
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     str
dtypes: float64(2), str(2)
memory usage: 452.0 bytes

In [87]:
df.describe()

             Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [88]:
df.isnull().sum()    # to find #nulls , sum() is to the show how many nulls per column

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [89]:
df

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3  Germany  40.0      NaN       Yes
4    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [90]:
print(df.duplicated().sum())    # to calculate no of dupliates and count

0

In [91]:
# for independent and dependent variable do column split

#split independent varibales
x=df.iloc[:,:-1].values      # show data for all column except the last column i.e -1
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Germany' 40.0 nan]
 ['Spain' 38.0 61000.0]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]

In [92]:
#split dependent variables 
y= df.iloc[:,3].values
print(y)

<StringArray>
['No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes']
Length: 10, dtype: str

In [93]:
 # no of row and columns
print(df.shape)

(10, 4)

In [94]:
#print(df)
df

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3  Germany  40.0      NaN       Yes
4    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [95]:
from sklearn.impute import SimpleImputer

# To handle missing values
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# Calculate the mean and fit the imputer
imputer = imputer.fit(x[:, 1:3])

# Replace missing values with the mean
x[:, 1:3] = imputer.transform(x[:, 1:3])

# Print the updated data
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Germany' 40.0 63777.77777777778]
 ['Spain' 38.0 61000.0]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]

In [96]:
# Encoding categorical data
# Encoding independent variable

from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelEncoder_x = LabelEncoder()

x[:, 0] = labelEncoder_x.fit_transform(x[:, 0])

print(x)

[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [1 40.0 63777.77777777778]
 [2 38.0 61000.0]
 [0 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]

In [97]:
# Encoding the inedependent variable 
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer([("Country", OneHotEncoder(),[0])],remainder="passthrough")
x=ct.fit_transform(x)
x.astype(int)

array([[    1,     0,     0,    44, 72000],
       [    0,     0,     1,    27, 48000],
       [    0,     1,     0,    30, 54000],
       [    0,     1,     0,    40, 63777],
       [    0,     0,     1,    38, 61000],
       [    1,     0,     0,    35, 58000],
       [    0,     0,     1,    38, 52000],
       [    1,     0,     0,    48, 79000],
       [    0,     1,     0,    50, 83000],
       [    1,     0,     0,    37, 67000]])

In [98]:
#Encoding the depoendent variable
from sklearn.preprocessing import LabelEncoder
labelEncoder_y = LabelEncoder()
y= labelEncoder_y.fit_transform(y)
y

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [99]:
# Split data into Training set and Test set
from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=45)

In [100]:
x_train.astype(int)
x_test

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0]], dtype=object)

In [101]:
x_train.astype(int)

array([[    0,     0,     1,    27, 48000],
       [    0,     1,     0,    50, 83000],
       [    1,     0,     0,    37, 67000],
       [    0,     0,     1,    38, 52000],
       [    1,     0,     0,    35, 58000],
       [    1,     0,     0,    48, 79000],
       [    1,     0,     0,    44, 72000],
       [    0,     1,     0,    40, 63777]])

In [102]:
#Feature Scaling 
# sc_x = (x[1]-mean) / standard deviation
# For classification sc 
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.fit_transform(x_test)

In [103]:
x_test

array([[ 0.,  1., -1., -1., -1.],
       [ 0., -1.,  1.,  1.,  1.]])

In [104]:
x_train

array([[-1.        , -0.57735027,  1.73205081, -1.87119123, -1.49264544],
       [-1.        ,  1.73205081, -0.57735027,  1.44646688,  1.51893703],
       [ 1.        , -0.57735027, -0.57735027, -0.42873118,  0.14221362],
       [-1.        , -0.57735027,  1.73205081, -0.17229384, -1.14846458],
       [ 1.        , -0.57735027, -0.57735027, -0.71722319, -0.6321933 ],
       [ 1.        , -0.57735027, -0.57735027,  1.15797487,  1.17475618],
       [ 1.        , -0.57735027, -0.57735027,  0.58099085,  0.57243968],
       [-1.        ,  1.73205081, -0.57735027,  0.00400683, -0.13504318]])